name: GitHub Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

        ############################
        # Install all modules #
        ############################
      - name: install modules
        run: yarn install

        #################
        # Build project #
        #################
      - name: build project
        run: yarn build

        #############
        # Lint code #
        #############
      - name: lint code
        run: yarn lint

        #############
        # Run tests #
        #############
      - name: run test
        run: yarn test

