name: GitHub Actions
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

        #################
        # Build project #
        #################
      - name: build project
        run: yarn build

        #################
        # Install yarn #
        ################
      - name: install yarn
        run: npm -g install yarn@1.22.15

        ############################
        # Install all dependencies #
        ############################
      - name: install all dependencies
        run: yarn install

